services:
  # Backend Service (Node.js)
  - type: web
    name: chat-backend
    env: node
    buildCommand: |
      cd backend
      npm ci
    rootDir: backend
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
    plan: free
    startCommand: npm start

  # Frontend Service (Static Site)
  - type: static_site
    name: chat-frontend
    buildCommand: |
      cd frontend
      npm ci
      npm run build
    rootDir: frontend
    outputDir: dist
    envVars:
      - key: VITE_API_URL
        value: https://chat-backend.onrender.com
      - key: NODE_ENV
        value: production
    plan: free
