services:
  # Backend Service
  - type: web
    name: chat-backend
    env: node
    build:
      command: |
        cd backend
        npm install
      publish: backend
    envVars:
      - key: PORT
        value: 10000
    plan: free

  # Frontend Service
  - type: web
    name: chat-frontend
    env: node
    build:
      command: |
        cd frontend
        npm install
        npm run build
      publish: frontend/dist
    envVars:
      - key: VITE_API_URL
        value: https://chat-backend.onrender.com
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    plan: free
