services:
  # Backend Service
  - type: web
    name: chat-backend
    env: node
    buildCommand: |
      cd backend
      npm ci
    rootDir: backend
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production
    plan: free
    startCommand: cd backend && npm start

  # Frontend Service
  - type: web
    name: chat-frontend
    env: node
    buildCommand: |
      cd frontend
      npm ci
      npm run build
    rootDir: frontend
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://chat-backend.onrender.com
      - key: NODE_ENV
        value: production
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
    plan: free
