services:
  # Backend Service (Node.js WebSocket Server)
  - type: web
    name: chat-backend
    env: node
    rootDir: backend
    plan: free
    buildCommand: npm ci
    startCommand: npm start
    envVars:
      - key: PORT
        value: 10000
      - key: NODE_ENV
        value: production

  # Frontend Service (React + Vite)
  - type: web  # 🔁 fixed: was static_site
    name: chat-frontend
    env: static  # this tells Render it's a static site
    rootDir: frontend
    plan: free
    buildCommand: |
      npm ci
      npm run build
    staticPublishPath: dist
    envVars:
      - key: VITE_API_URL
        value: https://chat-backend.onrender.com
      - key: NODE_ENV
        value: production
